import type { Metadata } from "next";
import "./globals.css";

// import de la fuente de Google Fonts
import { Quicksand } from "next/font/google"

// Fuente de Google Fonts
const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-quicksand",
})

export const metadata: Metadata = {
  title: "Club de Leones",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
