/* tslint:disable */
/* eslint-disable */


/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c postgres://username:password@club-leones.cxscice4ikfm.us-east-2.rds.amazonaws.com:5432/Pruebas?ssl=true&sslrootcert=./us-east-2-bundle.pem -t users -s public
 *
 */


export type Json = unknown;

// Table users
export interface Users {
  id: number;
  nombre: string;
  email: string;
}
export interface UsersInput {
  id?: number;
  nombre: string;
  email: string;
}
const users = {
  tableName: 'users',
  columns: ['id', 'nombre', 'email'],
  requiredForInsert: ['nombre', 'email'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Users,
  $input: null as unknown as UsersInput
} as const;


export interface TableTypes {
  users: {
    select: Users;
    input: UsersInput;
  };
}

export const tables = {
  users,
}
