/* tslint:disable */
/* eslint-disable */


/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c postgres://username:password@club-leones.cxscice4ikfm.us-east-2.rds.amazonaws.com:5432/Pruebas?ssl=true&sslrootcert=./certificates/us-east-2-bundle.pem -t competidor -t users -s public
 *
 */


export type Json = unknown;

// Table competidor
export interface Competidor {
  id_competidor: number;
  nombre: string;
  apellido_paterno: string;
  apellido_materno: string | null;
  fecha_nacimiento: Date | null;
  genero: string | null;
  email: string;
  telefono: string | null;
  contraseña: string;
  fecha_registro: Date | null;
  id_categoria: number | null;
}
export interface CompetidorInput {
  id_competidor?: number;
  nombre: string;
  apellido_paterno: string;
  apellido_materno?: string | null;
  fecha_nacimiento?: Date | null;
  genero?: string | null;
  email: string;
  telefono?: string | null;
  contraseña: string;
  fecha_registro?: Date | null;
  id_categoria?: number | null;
}
const competidor = {
  tableName: 'competidor',
  columns: ['id_competidor', 'nombre', 'apellido_paterno', 'apellido_materno', 'fecha_nacimiento', 'genero', 'email', 'telefono', 'contraseña', 'fecha_registro', 'id_categoria'],
  requiredForInsert: ['nombre', 'apellido_paterno', 'email', 'contraseña'],
  primaryKey: 'id_competidor',
  foreignKeys: {},
  $type: null as unknown as Competidor,
  $input: null as unknown as CompetidorInput
} as const;

// Table users
export interface Users {
  id: number;
  nombre: string;
  email: string;
}
export interface UsersInput {
  id?: number;
  nombre: string;
  email: string;
}
const users = {
  tableName: 'users',
  columns: ['id', 'nombre', 'email'],
  requiredForInsert: ['nombre', 'email'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Users,
  $input: null as unknown as UsersInput
} as const;


export interface TableTypes {
  competidor: {
    select: Competidor;
    input: CompetidorInput;
  };
  users: {
    select: Users;
    input: UsersInput;
  };
}

export const tables = {
  competidor,
  users,
}
